site_name: RingCentral SDK for C#
site_url: https://github.com/tylerlong/ringcentral-csharp-docs
repo_url: https://github.com/tylerlong/ringcentral-csharp-docs.git
docs_dir: docs
theme: readthedocs
pages:
# Overview:
- ['index.md', 'Overview', 'RingCentral SDK for C#']

# Prerequisites:
- ['prerequisites/mac.md', 'Prerequisites', 'Mac OS X']
- ['prerequisites/windows.md', 'Prerequisites', 'Windows']
