site_name: RingCentral C# SDK
site_url: https://github.com/tylerlong/ringcentral-csharp-docs
repo_url: https://github.com/tylerlong/ringcentral-csharp-docs.git
docs_dir: docs
theme: readthedocs
pages:
# Overview:
- ['index.md', 'Overview', 'RingCentral C# SDK']
- ['requirements.md', 'Overview', 'System Requirements']
# Xamarin Studio on Mac OS X
- ['installation.md', 'Xamarin Studio on Mac OS X', 'Installation']
- ['authentication.md', 'Xamarin Studio on Mac OS X', 'Authentication']
